# Adapted from https://github.com/JamesIves/github-pages-deploy-action
name: Build and Deploy Scroll
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Install and Build
        run: |
          npm install -g scroll-cli
          scroll build
          # The line below is needed if you have *.html in your gitignore file
          rm .gitignore
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: scroll-output # The branch the action should deploy to.
          folder: .
